/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms'

export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      // Tokens de Material Design 3 — copiados 1:1 del diseño source
      colors: {
        'tertiary-fixed': '#fcdeb5',
        'secondary-fixed': '#e1e2ed',
        'inverse-surface': '#2d3133',
        'on-tertiary-fixed-variant': '#574425',
        'surface-container-low': '#f2f4f6',
        outline: '#76777d',
        'primary-container': '#131b2e',
        'tertiary-container': '#271901',
        surface: '#f7f9fb',
        'tertiary-fixed-dim': '#dec29a',
        'on-background': '#191c1e',
        'on-tertiary-fixed': '#271901',
        'surface-container': '#eceef0',
        'on-error-container': '#93000a',
        'surface-bright': '#f7f9fb',
        'surface-container-high': '#e6e8ea',
        'primary-fixed-dim': '#bec6e0',
        'on-tertiary-container': '#98805d',
        'on-secondary': '#ffffff',
        secondary: '#5c5e68',
        'on-secondary-fixed': '#191b24',
        'surface-container-highest': '#e0e3e5',
        'surface-variant': '#e0e3e5',
        'on-tertiary': '#ffffff',
        tertiary: '#000000',
        error: '#ba1a1a',
        'inverse-on-surface': '#eff1f3',
        'secondary-fixed-dim': '#c4c6d1',
        'on-primary-fixed-variant': '#3f465c',
        'on-secondary-container': '#60626c',
        'inverse-primary': '#bec6e0',
        'on-secondary-fixed-variant': '#444650',
        'error-container': '#ffdad6',
        primary: '#000000',
        'on-surface': '#191c1e',
        'on-primary': '#ffffff',
        'on-surface-variant': '#45464d',
        'secondary-container': '#dedfeb',
        'primary-fixed': '#dae2fd',
        background: '#f7f9fb',
        'on-primary-container': '#7c839b',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'outline-variant': '#c6c6cd',
        'surface-dim': '#d8dadc',
        'surface-tint': '#565e74',
        'on-primary-fixed': '#131b2e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      boxShadow: {
        ambient: '0 10px 30px rgba(15, 23, 42, 0.04)',
      },
    },
  },
  plugins: [forms],
}
